---
- name: Install node
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - identify_port
    - horcrux_install
    - horcrux_configure
    - horcrux_create_shares

