---
- name: Shut down old ones
  hosts: old_hosts
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - horcrux_shutdown

- name: Install node
  hosts: new_hosts
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - horcrux_install
