---
- name: Define hosts
  hosts: localhost
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  tasks:
    - name: add single signer
      when: shares == 1
      add_host: 
        hostname: signer1
        group: signers
    
    - name: add all signers
      when: shares > 1
      add_host: 
        hostname: '{{ item }}'
        group: signers
      loop: '{{ groups["all"] }}'

- name: Backup Horcrux
  hosts: signers
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - backup
    - horcrux_shutdown

- name: Install Horcrux
  hosts: signers
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - identify_port
    - horcrux_install
    - horcrux_configure
    - horcrux_create_shares
