---
- name: Define hosts
  hosts: localhost
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  tasks:
    - name: handle mainnet signers
      when: testnet is not defined
      block:
        - name: add single signer
          when: shares == 1
          add_host: 
            hostname: signer1
            group: signers
        
        - name: add all signers
          when: shares > 1
          block:
            - name: remove testnet_signer1 from the list
              set_fact:
                filtered_list: "{{ groups['all'] | difference(['testnet_signer1']) }}"
            - name: create host group
              add_host: 
                hostname: '{{ item }}'
                group: signers
              loop: '{{ filtered_list }}'

    - name: handle testnet signers
      when: testnet is defined and testnet|bool
      add_host:
        hostname: testnet_signer1
        group: signers

- name: Install Horcrux
  hosts: signers
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - define_variables
    - backup
    - horcrux_configure
    - horcrux_restart
