---
- name: Move key
  block:
    - name: Copy keys
      copy:
        src: "keys/priv_validator_key.json"
        dest: "{{ horcrux_dir }}/{{ chain_id }}_priv_validator_key.json"
        owner: "{{ horcrux_user }}"
        group: "{{ horcrux_user }}"
        mode: '0400'

    - name: Find remote key share
      stat:
        path: "{{ horcrux_dir }}/{{ chain_id }}_priv_validator_key.json"
      register: share_moved

    - name: Delete priv_validator_key.json
      become: false
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/keys/priv_validator_key.json"
        state: absent
      run_once: true
      when: share_moved.stat.exists
