---
- name: Generate and move keys
  block:
    - name: Generate ECIES shards
      delegate_to: localhost
      run_once: true
      shell: |
        cd {{ playbook_dir }}/keys
        {{ item }}
      loop:
        - "../hostbin/horcrux create-ecies-shards --shards {{ shares }}"
        - "../hostbin/horcrux create-ed25519-shards --chain-id {{ chain_id }} --key-file ./priv_validator_key.json --threshold {{ threshold }} --shards {{ shares }}"    

    - name: Move keys to remote host
      block:
        - name: Find local key share
          delegate_to: localhost
          become: false
          stat:
            path: "{{ playbook_dir }}/keys/cosigner_{{ my_share}}/{{ item }}"
          register: has_share

        - name: Copy keys
          copy:
            src: "keys/cosigner_{{ my_share}}/{{ item }}"
            dest: "{{ horcrux_dir }}/{{ item }}"
            owner: "{{ horcrux_user }}"
            group: "{{ horcrux_user }}"
            mode: '0400'
          when: has_share.stat.isreg is defined and has_share.stat.isreg

        - name: Find remote key share
          stat:
            path: "{{ horcrux_dir }}/{{ item }}"
          register: share_moved

        - name: Delete local share
          become: false
          delegate_to: localhost
          file:
            path: "{{ playbook_dir }}/keys/cosigner_{{ my_share}}/{{ item }}"
            state: absent
          when: share_moved.stat.exists
      loop:
        - "{{ chain_id }}_shard.json"
        - "ecies_keys.json"

    - name: Delete priv_validator_key.json
      become: false
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/keys/priv_validator_key.json"
        state: absent
      run_once: true
      when: share_moved.stat.exists
