---
- name: Copy Horcrux dir
  copy:
    remote_src: true
    src: "{{ horcrux_dir }}/"
    dest: "{{ horcrux_home }}/.horcrux/b.{{ target }}/"

- name: Delete old Horcrux dir
  file:
    path: "{{ horcrux_dir }}/"
    state: absent

- name: Backup Horcrux binary
  copy:
    src: "{{ horcrux_home }}/go/bin/horcrux"
    dest: "{{ horcrux_home }}/go/bin/b.horcrux"
    remote_src: true

- name: Backup Horcrux service file
  become: true
  copy:
    src: "/etc/systemd/system/{{ service_file }}"
    dest: "/etc/systemd/system/b.{{ service_file }}"
    remote_src: true
