signMode: threshold
thresholdMode:
  threshold: {{ threshold }}
  cosigners:
{% for peer in horcrux_peers %}
  - shardId: {{ peer.share_id }}
    p2pAddr: tcp://{{ peer.p2p_addr }}:2{{ signer_port }}
{% endfor %}
  grpcTimeout: {{ rpc_timeout }}
  raftTimeout: {{ raft_timeout }}
chainNodes:
{% for sentry in sentries %}
- privValAddr: tcp://{{ sentry }}
{% endfor %}
debugAddr: ""
