---
- name: get servers from backend
  run_once: true
  block:
    - name: curl backend for servers
      ansible.builtin.uri:
        url: https://api.lavenderfive.com/servers/
        method: GET
        return_content: true
        headers:
          Authorization: "Api-Key {{ backend_api_key }}"
      register: servers_request

    - name: save server json
      when: servers_request.status == 200
      set_fact:
        all_servers: "{{ servers_request.json }}"

    - name: create sentry list
      when: all_servers is defined
      block:
        - name: define network servers
          set_fact:
            sentries: "{{ all_servers[network].values() | flatten | map('regex_replace', '$', ':' + signer_port + '59') | list }}"
