---
- name: get custom port prefix
  import_tasks: get_port_prefix.yml

- name: get servers
  ignore_errors: true
  when: 
    - backend_api_key is defined 
    - not whitelabel|bool
    - testnet is not defined
    - sentries is not defined
  include_tasks: get_servers.yml
