---
- name: check if Horcrux user exists
  stat:
    path: '/home/{{ horcrux_user }}'
  register: user

- name: Setup user config
  when: not user.stat.exists
  block:
  - name: Setup User
    user:
      name: '{{ horcrux_user }}'
      home: '{{ horcrux_home }}'
      password: '{{ horcrux_password }}'
      shell: /bin/bash
      password_lock: true

  - name: Set authorized keys
    authorized_key:
      user: "{{ horcrux_user }}"
      key: "{{ pubkey_file }}"

  - name: Allow sudo for administrator
    copy:
      content: '{{ horcrux_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
      dest: '/etc/sudoers.d/{{ horcrux_user }}'

  - name: Open ssh port
    ufw:
      rule: allow
      proto: tcp
      from: "{{ item.p2p_addr }}"
    loop: "{{ horcrux_peers }}"
    when: shares > 1

  - name: Create alias file
    template:
      src: bash_aliases.j2
      dest: '{{ horcrux_home }}/.bash_aliases'
      owner: '{{ horcrux_user }}'
      group: '{{ horcrux_user }}'
      mode: '0644'
