---
- name: Check if horcrux has already been setup
  stat:
    path: '{{ horcrux_dir }}/state'
  register: dir

- name: Create horcrux directory and initial state files
  when: not dir.stat.exists
  block:
    - name: Create horcrux directory
      file:
        owner: '{{ horcrux_user }}'
        group: '{{ horcrux_user }}'
        state: directory
        path: '{{ horcrux_dir }}/state'
        mode: '0750'

    - name: Create state files
      template:
        src: priv_validator_state.json
        dest: "{{ horcrux_dir }}/state/{{ chain_id }}_{{ item }}"
        mode: '0600'
        owner: "{{ horcrux_user }}"
        group: "{{ horcrux_user }}"
        force: no
      with_items:
        - priv_validator_state.json
        - share_sign_state.json

- name: Copy horcrux service file
  notify: Restart Horcrux
  become: true
  template:
    src: 'horcrux.service.j2'
    dest: '/etc/systemd/system/{{ service_file }}'
    owner: root
    group: root
    mode: 600
  register: systemdunit

- name: configure horcrux
  notify: Restart Horcrux
  block:
    - name: configure multi-signer horcrux
      import_tasks: configure_multi_signer.yml
      when: shares > 1

    - name: configure single-signer horcrux
      import_tasks: configure_single_signer.yml
      when: shares == 1

- name: Pause restart to miss a few blocks
  pause:
    seconds: 7

- name: Restart Horcrux
  systemd:
    daemon_reload: yes
    name: "{{ service_file }}"
    state: restarted
    enabled: yes
  when: systemdunit.changed or config_multi.changed or config_single.changed
