---
- name: Pause restart to miss a few blocks
  pause:
    seconds: 7

- name: Restart Horcrux
  become: true
  systemd:
    daemon_reload: yes
    name: "{{ service_file }}"
    state: restarted
    enabled: yes
