---
- name: Restart Horcrux
  systemd:
    daemon_reload: yes
    name: "{{ service_file }}"
    state: restarted
    enabled: yes
  when: systemdunit.changed or config_multi.changed or config_single.changed
